Add Log Forwarding
miguelzakharia/aurelia-application-insights pull request #2
Opened 2017-04-17 20:30 UTC by RichiCoder1

Adds the ability to send `aurelia-logging` messages to app insights.

Fixes #1;

Sorry bout the package.json whitespace change. Not sure what happened there.

2017-04-20 17:49 UTC, miguelzakharia commented
Sorry that I have not been able to review this yet, I've had a very busy week. If I don't get to it today then I will certainly complete it this weekend.

2017-04-20 19:53 UTC, RichiCoder1 commented
No worries :). As the beleagured maintainer of some of my own FOSS stuff, I understand

2017-04-24 04:18 UTC, miguelzakharia requested changes

2017-04-24 04:18 UTC, miguelzakharia commented on src/logAppender.js
> +		if (!this._plugin.initialized) {
Line 136 in `application-insights` already checks if the plugin has been initialized. I don't think the checks in `logAppender` are necessary and `logAppender` probably shouldn't care about the plugin anyway, right?

2017-04-25 22:26 UTC, RichiCoder1 commented on src/logAppender.js
> +		if (!this._plugin.initialized) {
Ohh, good catch. It wasn't originally structured like that.

2017-04-25 22:57 UTC, RichiCoder1 commented
Addressed comments and corrected a bad assumption. Should be good to go.

2017-04-26 02:44 UTC, miguelzakharia approved these changes

2017-04-26 02:44 UTC, merged