Add `appinsights-props` attribute
miguelzakharia/aurelia-application-insights pull request #5
Opened 2017-04-26 04:00 UTC by RichiCoder1

Allows for associating arbitrary objects with click tracking.  Closes #4.

2017-04-26 04:01 UTC, RichiCoder1 commented
A lot happening here, so will happily take questions or comments.

2017-05-05 01:40 UTC, miguelzakharia requested changes
Two really minor things otherwise it's good to go.

2017-05-05 01:40 UTC, miguelzakharia commented on src/appinsights-props.js
> +	static inject = [Element];
Please use `@inject()` instead so it stays consistent with the other code.

2017-05-05 01:40 UTC, miguelzakharia commented on src/appinsights-props.js
> +		if (!(typeof newValue == 'object' && newValue !== null)) {
Consider `if(typeof newValue !== 'object' || newValue === null)` instead to make it easier to read.

2017-05-05 04:45 UTC, RichiCoder1 commented on src/appinsights-props.js
> +	static inject = [Element];
Oops. Yup. For some reason I wasn't sure if I could use decorators.

2017-05-08 14:10 UTC, miguelzakharia approved these changes

2017-05-08 14:11 UTC, merged

2017-05-08 14:11 UTC, miguelzakharia commented
I'll publish this to NPM later today or tomorrow.